config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  # Establish Active Record Association
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  # Forces articles to have a title & description of specified length
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 10_000 }
  # All created articles must have an author
  validates :user_id, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # Call helper on actions that work with a specific article in database
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  # New, edit, create, update, & destroy actions need a user to call them
  before_action :require_user, except: [:index, :show]

  # Actions only owners of articles can call
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # Grab 5 articles in database at a time
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    # Instance variable for new Article
    @article = Article.new
  end

  def edit
  end

  def create
    # New instance variable with title, description, and categories
    @article = Article.new(article_params)

    # Assign owner of article
    @article.user = current_user

    # Validation passed
    if @article.save
      # Flash green
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    # Validation failed
    else
      render 'new'
    end
  end

  def update
    # Validation passed
    if @article.update(article_params)
      # Flash green
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    # Validation failed
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    # Find and delete article
    @article.destroy

    # Notify user (flash red) and redirect to listing
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private 
  # Helper that creates instance variable and sets to specific article
  def set_article
    @article = Article.find(params[:id])
  end

  # Whitelist title, description, and categories parameters
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  # Protect articles from users other than creator and admin
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
    
end

app/views/articles/_article.html.erb
<!-- List each article with CRUD options -->
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <!-- Display article -->
        <div class="article-title custom_font">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <div class="custom_font">
            <%= truncate(article.description, length: 100) %>
          </div>
          <div class="article-meta-details">

            <!-- Display article metadata -->
            <small>Created by <%= article.user.username if article.user %> 
                    <%= time_ago_in_words(article.created_at) %> ago. Last updated <%= time_ago_in_words(article.updated_at) %> ago.
            </small>

          </div>
        </div>
        
        <!-- Render categories -->
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>

        <!-- Allow article actions only for article owners or admins -->
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this article?" }, 
                                          class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<!-- Display any errors -->
<%= render 'shared/errors', obj: @article %>

<!-- Partial for article submission form -->
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>

      <!-- Title -->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>

      <!-- Description -->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>

      <!-- Categories Selection -->
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Submit Button -->
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-info btn-lg" %>
        </div>
      </div>

    <% end %>

    <div class="center">
      [ <%= link_to "Cancel request and return to listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center" class="custom_font">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center" class="custom_font">Listing all articles</h1>

<!-- Pagination links -->
<div align="center">
  <%= will_paginate %>
</div>

<!-- List all articles in paginated form -->
<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center" class="custom_font">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center" class="custom_font"><%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

  <!-- Information about article author -->
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by</li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <!-- Article author -->
          <li class="article-title custom_font">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li>
            <small>
              <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
            </small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>

  <!-- Article text -->
  <hr>
  <div class="custom_font">
    <%= simple_format(@article.description) %>
  </div>
  <hr>

  <!-- Article's categories -->
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>

  <!-- Article modification actions -->
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this article?" }, 
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>