config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base

  # Establish Active Record Association
  has_many :article_categories
  has_many :articles, through: :article_categories

  # All categories created must follow these rules
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # Call helper on actions that work with a specific category in database
  before_action :set_category, only: [:edit, :update, :show]

  # Limit category privileges to admins
  before_action :require_admin, except: [:index, :show]

  def index
    # Grab 5 categories in database at a time
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    # Instance variable for new Category
    @category = Category.new
  end

  def create
    # New instance variable with name
    @category = Category.new(category_params)
    # Category created
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    # Errors while creating category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    # Validation passed
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    # Validation failed
    else
      render 'edit'
    end
  end

  def show
    # Display 5 categories at a time
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  # Whitelist name param
  def category_params
    params.require(:category).permit(:name)
  end

  # Helper that creates instance variable and sets to specific category
  def set_category
    @category = Category.find(params[:id])
  end

  # Method to restrict certain category actions to admins
  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<!-- Display any errors -->
<%= render 'shared/errors', obj: @category %>

<!-- User creation form -->

<%= form_for(@category, :html => { class: "form-horizontal", role: "form" }) do |f| %>
  <!-- Username -->
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %> 
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>

  <!-- Form Submission Button -->
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-info btn-lg" %>
    </div>
  </div>

<% end %>

<div class="center">
[ <%= link_to "Cancel request and return to listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center" class="custom_font">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center" class="custom_font">Listing all categories</h1>

<div align="center">
  <%= will_paginate %>
  <!-- Iterate through all categories and list them -->
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title custom_font">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li>
            <small>
              <%= pluralize(category.articles.count, "article") %>
            </small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center" class="custom_font">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center" class="custom_font"><%= "All " + @category.name + " articles" %></h1>

<!-- Pagination links -->
<div align="center">
  <!-- Admins can edit categories -->
  <% if logged_in? && current_user.admin? %>
    <div class="row" id="category_edit_link">
      <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
    </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>